#!/usr/bin/env bash
# Basic info script for screenshot

# Copyright (c) 2013-2016 Jason W Ryan
# The MIT License (MIT) http://opensource.org/licenses/MIT

# installed window managers
wms=(dwm echinus i3 monsterwm scrotwm)

# colours
lt=$'\e[1;36m' # light cyan
dk=$'\e[0;36m' # dark cyan
tx=$'\e[1;32m' # green text
ec=$'\e[0m'

# details
machine=$(</proc/sys/kernel/hostname)
arch=$(uname -m)
mykernel=$(uname -r)
mycpu=$(awk '
  /cpu/ {flag=1} /!/ {flag=0} flag && /Intel/ \
    {sub(/\(TM\)/,"")
    print $5,$6,$8,$9;exit}
  ' /proc/cpuinfo)
myuptime=$(awk '
  { gsub(/,/,"")
    print (NF==10) ? $3 : $3" "$4" "$5}
  ' <(uptime))
myterm="$TERM"
myshell="${SHELL##*/}"
myedit="${EDITOR##*/}"
mybrowser="${BROWSER##*/}"


# if X is running
if [[ $DISPLAY ]]; then
    # check for running wm
    for w in "${wms[@]}"; do
        if pgrep -x "$w" &>/dev/null; then
        wm="$w" 
        break
        fi
    done

    myres=$(awk '/current/ {print $8,$9,+$10}' <(xrandr 2>/dev/null))
    myfont=$(awk -F: '/^URxvt.font/ {print $3}' ~/.Xresources)
    # screenshot command
    shot="scrot -cd5 ${machine}-$(date +%d%m%y).png"
else
    myres="Framebuffer"
    wm="TTY"
    myfont=$(awk -F= '/^FONT/ {print $2}' /etc/vconsole.conf)
    # screenshot command
    shot="fbgrab -s5 fbgrab.png"
fi

# ASCII goodness…
  cat <<EOF
${lt}                 +
                 #                 ${tx}Machine:${ec} ${machine}${lt}
                ###                ${tx}Architecture:${ec} ${arch}${lt}
               #####               ${tx}Kernel:${ec} ${mykernel}${lt}
               ######              ${tx}CPU:${ec} ${mycpu}${lt}
              ; #####;             ${tx}Uptime:${ec} ${myuptime}${lt}
             +##.#####             ${tx}Resolution:${ec} ${myres}${lt}
            +##########            ${tx}Window Manager:${ec} ${wm}${lt}
           #####${dk}######${lt}##;          ${tx}Shell:${ec} ${myshell^}${lt}
          ###${dk}############${lt}+         ${tx}Terminal:${ec} ${myterm^}${lt}
         #${dk}######   #######         ${tx}Editor:${ec} ${myedit^}${dk}
       .######;     ;###;\`.        ${tx}Browser:${ec} ${mybrowser^}${dk}
      .#######;     ;#####.        ${tx}Font:${ec} ${myfont^}${dk}
      #########.   .########\`
     ######'           '######
    ;####                 ####;
    ##'                     '##
   #'                         \`#
  '                            \`${ec}

EOF
${shot}
