#!/bin/sh
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White

# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White

# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White

# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White

printf "${BICyan}Bypassing NASA mainframe ...\n" && sleep 0.05 && printf "${PURPLE}Injecting virus ....\n" && printf "${BIGreen}Bypassing AES-256 BIT encryption ... \n" && printf "${BIYellow}Encryption bypassed. \n" && sleep 1.5 && dmesg 
sleep 0.5 && timeout 0.30 env LC_ALL=C tr -c "[:digit:]" " " < /dev/urandom | dd cbs=$(tput cols) conv=unblock | GREP_COLOR="1;35" grep --color "[^ ]"

printf "${PURPLE}SQL 2.610.9 outdated version detected, exploit?\n\n"
read -p "Exploit? (y/n) " exploit

if  [ "$exploit" = "y" ] ; then
	printf "${UCyan}Bypassing datacenter passwords"
	printf "${UPurple}\nSuccess, passwords obtained"
	printf "${UYellow}\nPerforming system scan"

	for i in 1 2 3 4 5 6 7 8 9 10
	do
		printf "${Cyan}Scanning ...\n"
		printf "${Yellow}Scanning ....\n"
		printf "${Blue}Scanning ....\n"
		sleep 0.01
	done
	printf "${UYellow}Gentoo automated install v1.5.7\n$(sleep 0.05)${UPurple}Establishing network connections...\nPartitioning disks...\n${URed}Creating EXT4 File System on /dev/sda1\n${UBlue}Mounting /dev/sda1 at /mnt/gentoo\n${UGreen}Downloading stage3 from distfiles.gentoo.org...\n$(sleep 1)${UCyan}Download completed (250MB/s)\n${UGREEN}Extracting stage3-amd64-20160822.tar.bz2 to /mnt/gentoo ...$(sleep 0.50)\n${UPurple}Extraction complete, settings anti lennart, freedesktop, wayland and GNOME USE flags $(sleep 0.05)downloading and installing precompiled pf-kernel (pf-sources), bootloader (GRUB2), installing grub and generating config (custom detection scripts)\n${UGreen}Setting up chroot environment ...\nSetting timezone to autodetected location ...\n${UBlue}Installing runit and cloning dotfiles for custom init scripts ...\n Purging OpenRC and SysVinit ...\n${UGreen}Install completed, you may reboot now.\n"
fi
