#!/bin/sh

# Import settings
realpath=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
. $realpath/panel-settings

# Volume Notification
CURVOL="$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/%.*//g')"

 (
echo "Volume"
echo $CURVOL
 ) | dzen2 \
    -p "1" \
    -x "5" \
    -y "5" \
    -w "100" \
    -h "28" \
    -l "1" \
    -sa "c" \
    -ta "c" \
    -title-name "dzen2-vol-not" \
    -e "onstart=uncollapse;button1=exit;button3=exit" \
    -fn "${PANEL_FONT_FAMILY}:pixelsize=${NOT_FONT_SIZE}" \
    -bg "$PANEL_COLOR_BACKGROUND" \
    -fg "$PANEL_COLOR_FOREGROUND" &
