#!/bin/sh 

# Import settings
realpath=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
. $realpath/panel-settings

 (
echo "Disk"
echo "root: $(df -h / | sed '1d' | awk '{print $3}') / $(df -h / | sed '1d' | awk '{print $2}')"
echo "home: $(df -h $HOME/dev | sed '1d' | awk '{print $3}') / $(df -h $HOME/dev | sed '1d' | awk '{print $2}')"
echo "Data: $(df -h $HOME/dev/Data | sed '1d' | awk '{print $3}') / $(df -h $HOME/dev/Data | sed '1d' | awk '{print $2}')"
 ) | dzen2 \
    -p "5" \
    -x "1310" \
    -y "27" \
    -w "180" \
    -l "4" \
    -h "18" \
    -sa "c" \
    -ta "c" \
    -title-name "dzen2-disk" \
    -e "onstart=uncollapse;button1=exit;button3=exit" \
    -fn "${PANEL_FONT_FAMILY}:pixelsize=${PANEL_FONT_SIZE}" \
    -bg "$PANEL_COLOR_BACKGROUND" \
    -fg "$PANEL_COLOR_FOREGROUND" &
