#!/bin/sh

# Import settings
realpath=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
. $realpath/panel-settings

# Get Link
IP_LINK="$(ip route | grep 'via' | awk '{print $5}' | head -n 1)"
INTIP_ADDR="$(ip addr show $IP_LINK | grep 'inet' | awk '{print $2}' | head -n 1)"
EXTIP_ADDR="$(dig +short myip.opendns.com @resolver1.opendns.com)"

 (
echo "Network" 
echo "IP: "$INTIP_ADDR
echo "EXIP: "$EXTIP_ADDR
if [[ $IP_LINK == $SYS_WLAN_INTERFACE ]]; then
    SSID="$(iwconfig wlo1 | grep ESSID | awk '{print $4}')"
    echo $SSID
fi
 ) | dzen2 \
    -p "4" \
    -x "1150" \
    -y "27" \
    -w "170" \
    -l "3" \
    -h "18" \
    -sa "c" \
    -ta "c"\
    -title-name 'dzen2-net'\
    -e "onstart=uncollapse;button1=exit;button3=exit" \
    -fn "${PANEL_FONT_FAMILY}:pixelsize=${PANEL_FONT_SIZE}" \
    -bg "$PANEL_COLOR_BACKGROUND" \
    -fg "$PANEL_COLOR_FOREGROUND" &
