#!/bin/sh

# Import settings
realpath=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
. $realpath/panel-settings

 (
echo "☼"
 ) | dzen2 \
    -p \
    -x "1550" \
    -y "850" \
    -w "45" \
    -h "45" \
    -l "0" \
    -sa "c" \
    -ta "c" \
    -title-name "dzen2-xautolock-not" \
    -e "onstart=uncollapse" \
    -fn "Dejavu Sans Mono:pixelsize=44" \
    -bg "$PANEL_COLOR_BACKGROUND" \
    -fg "$PANEL_COLOR_FOREGROUND" &
