#!/usr/bin/env bash
# from https://bbs.archlinux.org/viewtopic.php?pid=1231045#p1231045

inf="${1}"
outf="${2}"

printf "%s\n" "File: $inf"

flac -scd "$inf" | oggenc -o "$outf" -q "${quality:-7}" -

metaflac "$inf" --export-tags-to=- \
    | perl -ne 'if (m/^([\w]+)\=/) {print "$1\n"}' \
    | while read tag; do
        metaflac "$inf" --show-tag="$tag" \
            | perl -0777pe 's/\n$//;s/\//\/\//g;s/[\n\r]/\\n/g;s/(.)$/$1\n/'
    done | vorbiscomment -ea "$outf"
