#!/bin/sh
set -eu

if [ "$1" = "now" ] ; then
	curl --silent "http://wttr.in" | head -n 7 | tail -n 5
fi

if [ "$1" = "today" ] ; then
	curl --silent http://wttr.in | head -n 17 | tail -n 9
fi

if [ "$1" =  "tomorrow" ] ; then
	curl --silent http://wttr.in | head -n 27 | tail -n 9
fi

if [ "$1" = "all" ] ; then
	curl --silent http://wttr.in | head -n 37 | tail -n 35
fi

if [ "$1" = "2days" ] ; then
	curl --silent http://wttr.in | head -n 37 | tail -n 10
fi
